name: deploy-workflow
on: [push]
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2 # [H]
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/webapp/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn-lock.json') }}-${{ hashFiles('**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - run: yarn
      - run: yarn workspace webapp run build -o static-pages
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated publish